# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fileinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.FloatField(default=0.0)),
                ('cadence', models.FloatField(default=0.0)),
                ('distance', models.FloatField(default=0.0)),
                ('enhanced_altitude', models.FloatField(default=0.0)),
                ('enhanced_speed', models.FloatField(default=0.0)),
                ('fractional_cadence', models.FloatField(default=0.0)),
                ('position_lat', models.IntegerField(default=0)),
                ('position_long', models.IntegerField(default=0)),
                ('speed', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField()),
                ('fileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitparser.Fileinfo')),
            ],
        ),
    ]
