# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.FloatField(default=0.0)),
                ('cadence', models.FloatField(default=0.0)),
                ('distance', models.FloatField(default=0.0)),
                ('enhanced_altitude', models.FloatField(default=0.0)),
                ('enhanced_speed', models.FloatField(default=0.0)),
                ('fractional_cadence', models.FloatField(default=0.0)),
                ('position_lat', models.IntegerField(default=0)),
                ('position_long', models.IntegerField(default=0)),
                ('speed', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
